resources:
  network:
    type: network

  subnet:
    type: subnet
    properties:
      network_id: network
      cidr: random
      ip_version: 4

  myrouter:
    type: router
    properties:
      external_gateway_info:
        network_id: local
        enable_snat: true

  routerInterface:
    type: router_interface
    properties:
      subnet_id: subnet
      router_id: myrouter

  instance1:
    type: server
    properties:
      name: instance1
      imageRef: local
      flavorRef: local
      security_groups:
        - name: sdn_test
      networks:
        - uuid: network
      adminPass: Wang.123
      block_device_mapping_v2:
        - boot_index: 0
          uuid: local
          source_type: image
          destination_type: volume
          volume_size: 10
          delete_on_termination: true

  fip1:
    type: floatingip
    properties:
      floating_network_id: local
      port_id: instance1

