# openstack keystone

SDN:
  SDNHost: 
  SDNUserName: 
  SDNPassword: 

##
Openstack:
  Host: 
  AdminPassword: 
  ProjectName: 
  UserName: 
  UserPassword: 
  ExternalNetwork: 
  ImageId: 
  FlavorId: 
